/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

// buildscript {
//   dependencies {
//     classpath("org.flywaydb:flyway-database-postgresql:11.17.0")
//   }
// }

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.flywaydb.flyway") version "11.17.0"
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

buildscript {
  dependencies {
    classpath("org.flywaydb:flyway-database-postgresql:11.17.0")
  }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation(libs.hibernate.core)
    implementation(libs.postgresql)
    implementation(libs.slf4j.simple)
    implementation(libs.hibernate.scan.jandex)
    annotationProcessor("org.hibernate.orm:hibernate-processor:7.1.1.Final")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.josafaverissimo.App"
}

flyway {
  url = "jdbc:postgresql://localhost:5432/java-hibernate"
  user = "postgres"
  password = "root"
  schemas = arrayOf("public", "prmx", "verttice")
  placeholders = mapOf("schema" to "public")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
